const testTypes = new Map([
  ['Straight', '直進'],
  ['Left', '左折'],
  ['Right', '右折'],
  ['Slight Left', '左方向'],
  ['Slight Right', '右方向'],
  ['testException', 'testException'],
]);

const testNotes = [
  {
    data: '高橋（交差点） を左折して 中央通り/​府道139号 に入る (枚方/​阪急茨木市駅 の表示)',
    crrosing: '高橋',
    routeJ: '府道139号',
    routeE: 'F139',
    routeK: 'K139',
    remark: '中央通り/​府道139号 に入る (枚方/​阪急茨木市駅 の表示)',
  },
  {
    data: '右折してそのまま 府道139号 を進む (枚方/​鮎川 の表示)',
    crrosing: '',
    routeJ: '府道139号',
    routeE: 'F139',
    routeK: 'K139',
    remark: 'そのまま 府道139号 を進む (枚方/​鮎川 の表示)',
  },
  {
    data: '左折して府道132号に入る (高槻 の表示)',
    crrosing: '',
    routeJ: '府道132号',
    routeE: 'F132',
    routeK: 'K132',
    remark: '府道132号に入る (高槻 の表示)',
  },
  {
    data: '左折する',
    crrosing: '',
    routeJ: '',
    routeE: '',
    routeK: '',
    remark: '',
  },
  {
    data: '右折する',
    crrosing: '',
    routeJ: '',
    routeE: '',
    routeK: '',
    remark: '',
  },
  {
    data: '中川町（交差点） を右折して 国道171号 に入る',
    crrosing: '中川町',
    routeJ: '国道171号',
    routeE: 'R171',
    routeK: 'R171',
    remark: '国道171号 に入る',
  },
  {
    data: '桃園町（交差点） を左折する',
    crrosing: '桃園町',
    routeJ: '',
    routeE: '',
    routeK: '',
    remark: '',
  },
  {
    data: '右折して 新川いちょう通り に向かう',
    crrosing: '',
    routeJ: '',
    routeE: '',
    routeK: '',
    remark: '新川いちょう通り に向かう',
  },
  {
    data: '斜め左方向に曲がり新川いちょう通りに入る',
    crrosing: '',
    routeJ: '',
    routeE: '',
    routeK: '',
    remark: '',
  },
  {
    data: '右折して西国街道に入る',
    crrosing: '',
    routeJ: '',
    routeE: '',
    routeK: '',
    remark: '西国街道に入る',
  },
  {
    data: '調子二丁目（交差点） を左折して 新西国街道/​物集女街道/​西国街道/​府道10号/​府道204号/​府道67号 に入る',
    crrosing: '調子二丁目',
    routeJ: '府道10号',
    routeE: 'F10',
    routeK: 'K10',
    remark:
      '新西国街道/​物集女街道/​西国街道/​府道10号/​府道204号/​府道67号 に入る',
  },
  {
    data: '千代原口（交差点）を直進して、そのまま府道29号へ進む (嵐山/​松尾 の表示)',
    crrosing: '千代原口',
    routeJ: '府道29号',
    routeE: 'F29',
    routeK: 'K29',
    remark: 'そのまま府道29号へ進む (嵐山/​松尾 の表示)',
  },
  {
    data: '松尾大社（交差点） を右折して 四条通/​四条通り/​市道186号/​府道29号 に入る (嵯峨/​嵐山 の表示)',
    crrosing: '松尾大社',
    routeJ: '府道29号',
    routeE: 'F29',
    routeK: 'K29',
    remark: '四条通/​四条通り/​市道186号/​府道29号 に入る (嵯峨/​嵐山 の表示)',
  },
  {
    data: '右折して 石山通/​道道452号 に向かう',
    crrosing: '',
    routeJ: '道道452号',
    routeE: 'D452',
    routeK: 'K452',
    remark: '石山通/​道道452号 に向かう',
  },
  {
    data: '大和陸橋（交差点） を左折して 環七通り/​都道318号 に入る (豊玉 の表示)',
    crrosing: '大和陸橋',
    routeJ: '都道318号',
    routeE: 'T318',
    routeK: 'K318',
    remark: '環七通り/​都道318号 に入る (豊玉 の表示)',
  },
  {
    data: '朝来インター東（交差点） を右折して 国道312号/​国道429号 に入る (姫路/​生野 の表示)',
    crrosing: '朝来インター東',
    routeJ: '国道312号',
    routeE: 'R312',
    routeK: 'R312',
    remark: '国道312号/​国道429号 に入る (姫路/​生野 の表示)',
  },
  {
    data: '県道81号を進む',
    crrosing: '',
    routeJ: '県道81号',
    routeE: 'K81',
    routeK: 'K81',
    remark: '',
  },
];

exports.testTypes = testTypes;
exports.testNotes = testNotes;
